version: '3.9'

services:
  qnode0_app:
    build:
      context: .
    command: >
        sh -c "
           python manage.py wait_for_db &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
      - 587:587
      - 25:25
    volumes:
      - ./qnode0_app:/qnode0_app
      - ./vol/data/web:/vol/web
    environment:
      - SECRET_KEY=ms95355672
      - DEBUG=1
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
      - DB_HOST=db
      - DB_NAME=QNODEDB
      - DB_USER=smartadmindb
      - DB_PASS=ms95355672
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=QNODEDB
      - POSTGRES_USER=smartadmindb
      - POSTGRES_PASSWORD=ms95355672
    ports:
      - "5432"

  redis:
    image: redis:3.0
